### ISSUE TITLE
First argument of `record<>` is parsed as keyword, not string

### ISSUE THREAD

**Issue by tabatkins** [plinss/widlparser#31]
When parsing something like `typedef record<DOMString, DOMString> Textmap;`, the second `DOMString` correctly gets parsed as a string (and calls `markupStringType()`), but the first one is parsed as a keyword (and calls `markupKeyword()` instead).  I don't understand the difference here.

This is currently causing a bug in the WASM spec <https://github.com/tabatkins/bikeshed/issues/1118#issuecomment-338773485>

**Comment by TimothyGu** [comment]
I believe this is a PEBKAC in 46e0bdcad55b3fda476e29af84a30871a5332a0e:

https://github.com/plinss/widlparser/blob/ea762e7f431a9fb123a4fe699a29d604dcb256fe/widlparser/productions.py#L612

should use `NonAnyType` instead of `Symbol` (or even better, `StringType` if that function is created).

**Comment by plinss** [comment]
This fix should so it. We don't want to parse the record keys as NonAnyTypes since they're restricted to string types. This merely corrects the markup calls to markup the keys as strings rather than bare keywords (so you should get a call to markupStringType(), with a nested call to markupKeyword(), like everywhere else).

**Comment by tabatkins** [comment]
:+1:
