### ISSUE TITLE
Implement required dictionary defaulting

### ISSUE THREAD

**Issue by annevk** [plinss/widlparser#39]
See https://github.com/heycam/webidl/pull/750.

**Comment by domenic** [comment]
Gentle ping on this :). A number of specs are waiting to merge until this is updated.

**Comment by plinss** [comment]
I added the "{}" to the Default production in 368c99b312f7764958e4ed8c12d1dde77b8b32df. But I'm guessing you also want a warning/error for when it's not present on an optional dictionary type.

The problem with that is knowing that the passed type is a dictionary or a union that has a dictionary member, and that would require a proper symbol table which widlparser doesn't have. It'd also require the type definition to have been previously parsed, which is often not the case for a WebIDL snippet... so that's likely out of scope for widlparser.

It wouldn't be too hard to add a symbol table, but Bikeshed (or other widlparser consumers) would have to do some work to keep a master symbol table and pass it in to widlparser instances for type resolution. It's not clear to me if we can rely on the dictionary type always being defined somewhere in the same spec as the optional usage or we'd have to maintain some kind of master symbol table for all the specs (which could be an interesting project in and of itself, maybe that can be derived from or combined with the anchor database somehow?)

I expect there are a bunch of other WebID validations that could be enabled by the symbol table...

**Comment by annevk** [comment]
Having errors would be ideal, but having basic support is a huge win already. Thanks for landing that!
